site_name: 课程心得及总结
site_description: A short description of my project.
site_author: Your Name
site_url: https://github.com/123axderg/123axderg.github.io
site_dir: site
repo_url: https://github.com/example/repository/
plugins:
  - glightbox
nav:
  - Home: home.md
  - About: about.md
  - 生理科学实验: 生理科学实验.md
  - 药理学: 药理学.md
theme:
  favicon: assets/favicon.ico
  name: material
